FROM golang:1.16 

WORKDIR /go/src

ENV PATH=${PATH}:"/go/bin"

RUN apt-get update && \
    apt-get install build-essential librdkafka-dev -y

COPY . .
RUN GOOS=linux go build -ldflags="-s -w" -o simulador
ENTRYPOINT [ "./simulador" ]
